from __future__ import annotations

from datetime import UTC, date, datetime
from decimal import Decimal

import pytest

from woo_security_simulator.domain.commerce import (
    Address,
    Cart,
    CartItem,
    Coupon,
    Customer,
    Order,
    OrderItem,
    PaymentMethod,
    Product,
    ProductCategory,
    ProductReview,
    ShippingMethod,
    StoreSettings,
    WishlistItem,
)
from woo_security_simulator.domain.enums import (
    AccountType,
    ActivityEventType,
    ActivityOutcome,
    AddressKind,
    BackupStatus,
    BackupType,
    ControlStatus,
    CoreComponentType,
    DiscountType,
    EnvironmentKind,
    EstimatedEffort,
    FindingStatus,
    OrderStatus,
    PaymentMethodKind,
    PaymentSimulationStatus,
    PluginStatus,
    ProductVisibility,
    RemediationPriority,
    RemediationStatus,
    RiskLevel,
    Severity,
    SnapshotKind,
    StockStatus,
    SupportStatus,
    ThemeStatus,
    UpdateStatus,
    VerificationStatus,
    VulnerabilityIndicator,
)
from woo_security_simulator.domain.security import (
    ActivityEvent,
    AuditSnapshot,
    BackupRecord,
    CoreComponent,
    Plugin,
    RemediationAction,
    ScanSummary,
    SecurityCategory,
    SecurityControl,
    SecurityFinding,
    SiteProfile,
    Theme,
    UserAccount,
)
from woo_security_simulator.metadata import SIMULATION_NOTICE

NOW = datetime(2026, 7, 30, 12, 0, tzinfo=UTC)


@pytest.fixture
def model_instances() -> tuple[object, ...]:
    billing = Address(
        "addr_billing",
        "customer_demo",
        AddressKind.BILLING,
        "Ada Sample",
        "10 Fiction Avenue",
        "Lagos",
        "Lagos",
        "100001",
        "NG",
    )
    shipping = Address(
        "addr_shipping",
        "customer_demo",
        AddressKind.SHIPPING,
        "Ada Sample",
        "10 Fiction Avenue",
        "Lagos",
        "Lagos",
        "100001",
        "NG",
    )
    order_item = OrderItem(
        "product_dock", "NS-DK-01", "Meridian Dock", Decimal("20.00"), 2, Decimal("40.00")
    )
    site = SiteProfile(
        "site_demo",
        "Northstar Desk & Living",
        EnvironmentKind.DEMONSTRATION,
        "https://northstar.example.test",
        "6.8.1",
        "9.9.0",
        "8.3.12",
        True,
        NOW,
    )
    return (
        ProductCategory("category_desk", "Desk Technology", "desk-technology", "Desk equipment."),
        Product(
            "product_dock",
            "NS-DK-01",
            "Meridian Dock",
            "meridian-dock",
            "A fictional USB-C dock.",
            "A compact fictional dock.",
            "category_desk",
            Decimal("25.00"),
            8,
            StockStatus.IN_STOCK,
            True,
            Decimal("4.5"),
            2,
            "assets/products/dock.webp",
            ("dock", "office"),
            ProductVisibility.VISIBLE,
            NOW,
            NOW,
            Decimal("20.00"),
            2,
            Decimal("0.5"),
            {"ports": "8"},
        ),
        ProductReview(
            "review_one", "product_dock", "Ada S.", 5, "Useful", "Fictional review.", NOW, True
        ),
        CartItem("product_dock", 2),
        Cart("cart_demo", (CartItem("product_dock", 2),), "DESK10", "shipping_standard", NOW),
        Coupon(
            "DESK10",
            DiscountType.PERCENTAGE,
            Decimal("10"),
            True,
            Decimal("20"),
            Decimal("25"),
            ("category_desk",),
            NOW,
            100,
        ),
        ShippingMethod(
            "shipping_standard",
            "Standard",
            "Fictional shipping.",
            Decimal("5.00"),
            True,
            Decimal("50"),
            2,
            5,
        ),
        PaymentMethod(
            "payment_demo",
            "Demo Card",
            "Selection only; no card details.",
            PaymentMethodKind.DEMO_CARD,
            True,
            SIMULATION_NOTICE,
        ),
        Customer(
            "customer_demo", "Ada Sample", "ada@example.test", NOW, "addr_billing", "addr_shipping"
        ),
        billing,
        order_item,
        Order(
            "order_demo",
            "NS-1001",
            "customer_demo",
            (order_item,),
            OrderStatus.PROCESSING,
            "payment_demo",
            PaymentSimulationStatus.AUTHORIZED_SIMULATION,
            "shipping_standard",
            billing,
            shipping,
            Decimal("40.00"),
            Decimal("5.00"),
            Decimal("5.00"),
            Decimal("40.00"),
            NOW,
            SIMULATION_NOTICE,
            "DESK10",
            "Fictional note.",
            NOW,
        ),
        WishlistItem("customer_demo", "product_dock", NOW),
        StoreSettings(
            "Northstar Desk & Living",
            "NGN",
            "₦",
            3,
            12,
            1,
            "Fictional store.",
            "Tax not calculated.",
        ),
        site,
        CoreComponent(
            "component_wp",
            "WordPress",
            CoreComponentType.WORDPRESS,
            "6.8.1",
            "6.8.1",
            UpdateStatus.CURRENT,
            SupportStatus.SUPPORTED,
        ),
        Plugin(
            "plugin_cache",
            "Northstar Cache Demo",
            "northstar-cache-demo",
            "1.0.0",
            PluginStatus.ACTIVE,
            UpdateStatus.CURRENT,
            date(2026, 7, 1),
            "Fictional Publisher",
            VulnerabilityIndicator.NONE_OBSERVED,
            "Fictional cache demonstration.",
        ),
        Theme(
            "theme_child",
            "Northstar Child",
            "1.0.0",
            ThemeStatus.ACTIVE,
            UpdateStatus.CURRENT,
            True,
            "theme_parent",
            "1.0.0",
            date(2026, 7, 1),
        ),
        UserAccount(
            "user_admin",
            "Amina Demo",
            "admin@example.test",
            AccountType.ADMINISTRATOR,
            True,
            True,
            ControlStatus.PASS,
            NOW,
            True,
        ),
        SecurityCategory("category_access", "Access", "Access-control posture.", 1),
        SecurityControl(
            "control_2fa",
            "category_access",
            "Administrator 2FA",
            "Administrators use 2FA.",
            ControlStatus.PASS,
            Severity.HIGH,
            "All fictional admins show 2FA enabled.",
            "Review the simulated account inventory.",
        ),
        SecurityFinding(
            "finding_plugin",
            "Outdated plugin",
            "category_access",
            Severity.HIGH,
            FindingStatus.OPEN,
            "plugin_cache",
            "A fictional plugin is behind.",
            "Fixture version comparison.",
            "An outdated component may increase risk.",
            "Review and apply the simulated update.",
            RemediationPriority.NEXT,
            EstimatedEffort.SMALL,
            "Version behind.",
            None,
            VerificationStatus.NOT_STARTED,
            ("control_2fa",),
        ),
        RemediationAction(
            "action_update",
            "finding_plugin",
            "Update plugin",
            RemediationPriority.NEXT,
            EstimatedEffort.SMALL,
            RemediationStatus.TODO,
            ("Confirm the simulated recommended version.",),
        ),
        ScanSummary(
            "snapshot_before",
            {"high": 1},
            {"pass": 1},
            5,
            10,
            RiskLevel.ELEVATED,
            NOW,
            "1.0",
            SIMULATION_NOTICE,
        ),
        AuditSnapshot(
            "snapshot_before",
            "Before hardening",
            SnapshotKind.BEFORE,
            NOW,
            site,
            ("component_wp",),
            {"control_2fa": ControlStatus.FAIL},
            {"finding_plugin": FindingStatus.OPEN},
            "1.0",
        ),
        BackupRecord("backup_one", NOW, NOW, BackupType.FULL, BackupStatus.SUCCEEDED, True, 30),
        ActivityEvent(
            "event_one",
            NOW,
            "Security engineer demo",
            ActivityEventType.SECURITY_REVIEW,
            "Reviewed fictional posture.",
            ActivityOutcome.SUCCESS,
            "component_wp",
            {"count": 1},
        ),
    )
