"""Repository contracts consumed by services."""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol, TypeVar

T = TypeVar("T")


class Repository(Protocol[T]):
    def list(self) -> tuple[T, ...]: ...
    def get(self, record_id: str) -> T: ...
    def find(self, predicate: Callable[[T], bool]) -> tuple[T, ...]: ...
    def add(self, item: T) -> None: ...
    def update(self, item: T) -> None: ...
    def delete(self, record_id: str) -> T: ...
    def replace_all(self, items: tuple[T, ...]) -> None: ...
    def exists(self, record_id: str) -> bool: ...
    def count(self) -> int: ...
